export enum Task {
  SHORT_DESTROY_GIANT_POOP, // Admin ()
  SHORT_BOMB_ROCKS,
  SHORT_IDENTIFY_ITEM,
  SHORT_IDENTIFY_TRINKET,
  SHORT_LOAD_SLOT_MACHINES,
  SHORT_MAKE_PENTAGRAM, // Black Powder
  SHORT_PRESS_BUTTONS_WITH_GRUDGE,
  SHORT_FIX_WIRES,
  SHORT_WALK_DIAGONALLY_THROUGH_SPIKES,
  SHORT_WALK_BETWEEN_SUCTION_PITFALLS,
  SHORT_WALK_BETWEEN_POKIES,
  SHORT_PUSH_TNT_BARREL,
  LONG_IDENTIFY_PICKUPS_IN_ORDER,
  LONG_BREAK_ASTEROIDS, // Analog Stick + Lost Contact
  LONG_COLLECT_GOLDEN_PENNY,
  LONG_KILL_WORMS,
  LONG_BUTTONS_BEHIND_KEY_BLOCKS,
  LONG_DODGE_RETRACTING_SPIKES,
  LONG_PUSH_BUTTONS_IN_ORDER,
  LONG_DODGE_STONE_SHOOTERS,
  LONG_DEFEAT_MONSTRO,
}
