export const IS_DEV = true;
export const TCP_PORT = 9122; // Arbitrarily chosen to not conflict with common IANA ports
export const UDP_PORT = 9123;
export const DEV_MIN_PLAYERS = 1;
export const MIN_PLAYERS = 4;
export const MAX_PLAYERS = 15;
export const NOT_VOTED_YET = -1;
export const VOTE_SKIP = -2;
export const EMERGENCY_BUTTON_COOLDOWN_SECONDS = 30;
